# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "13.0.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "i3.xlarge"

environments:
  dev:
    workflows:
      - name: "cali_housing_setup_data"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops 
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "main"
            description: "Workflow to setup data for the project"
            existing_cluster_id: "0420-014219-930j61s2"
            # <<: *basic-static-cluster
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/data_setup"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/dev/.dev.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/data_setup_cfg.yml']
              base_parameters: {"env" : "dev", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }
              # base_parameters: {"job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }

      - name: "cali_housing_model_train"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "main"
            description: "Workflow for model-train pipeline"
            existing_cluster_id: "0420-014219-930j61s2"
            # existing_cluster_id: "<existing_cluster_id>"
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/model_train"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/dev/.dev.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/model_train_cfg.yml']
              base_parameters: {"env" : "dev", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }         

      - name: "cali_housing_model_deployment"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "main"
            description: "Workflow for model deployment pipeline"
            existing_cluster_id: "0420-014219-930j61s2"
            # existing_cluster_id: "<existing_cluster_id>"
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/model_deployment"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/dev/.dev.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/model_deployment_cfg.yml']
              base_parameters: {"env" : "dev", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }
      - name: "cali_housing_model_inference_batch"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "main"
            description: "Workflow for model inference batch pipeline"
            existing_cluster_id: "0420-014219-930j61s2"
            # existing_cluster_id: "<existing_cluster_id>"
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/model_inference_batch"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/dev/.dev.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/model_inference_batch_cfg.yml']
              base_parameters: {"env" : "dev", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }
      - name: "cali_housing_model_train_and_deploy"
        description: "Workflow for model train and model deploy pipeline"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "train"
            description: "Task for model train pipeline"
            existing_cluster_id: "0420-014219-930j61s2"
            # existing_cluster_id: "<existing_cluster_id>"
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/model_train"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/dev/.dev.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/model_train_cfg.yml']
              base_parameters: {"env" : "dev", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }
          - task_key: "deploy"
            description: "Task for model deploy pipeline"
            depends_on: 
              - task_key: "train"
            existing_cluster_id: "0420-014219-930j61s2"
            # existing_cluster_id: "<existing_cluster_id>"
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/model_deploy"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/dev/.dev.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/model_deployment_cfg.yml']
              base_parameters: {"env" : "dev", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }

  staging:
    workflows:
      - name: "cali_housing_setup_data"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "main"
            description: "Workflow for model-train pipeline"
            <<: *basic-static-cluster
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/data_setup"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/staging/.staging.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/data_setup_cfg.yml']
              base_parameters: {"env" : "staging", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }

  prod:
    workflows:
      - name: "cali_housing_setup_data"
        git_source:
          git_url: https://github.com/Zaxier/packaged-poc-mlops
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "main"
            description: "Workflow for model-train pipeline"
            <<: *basic-static-cluster
            deployment_config:
              no_package: true # we omit using package since code will be shipped directly from the Repo
            notebook_task:
              notebook_path: "notebooks/cali_housing_mlops/data_setup"
              parameters: ['--base-data-params': 'file:fuse://conf/.base_data_params.env',
                           '--env', 'file:fuse://conf/prod/.prod.env',
                           '--conf-file', 'file:fuse://conf/pipeline_configs/cali_housing_mlops/data_setup_cfg.yml']
              base_parameters: {"env" : "prod", "job-id" : "{{job_id}}", "start-time" : "{{start_time}}" }