custom:
  model_name: 'cali_housing_rf' &model_name # Environment suffix will be added by code

model_train:
  mlflow_params:
    <<: *model_name
    run_name: 'new_forest'
  preproc_params:
    test_size: 0.33
    random_state: 42
  model_params:
    n_estimators: 150
    max_depth: 44
    min_samples_leaf: 1
    max_features: 'auto'
    random_state: 206


model_deployment:
  mlflow_params:
    <<: *model_name
  model_comparison_params:
    metric: 'r2_score'
    higher_is_better: True


model_inference_batch:
  mlflow_params:
    <<: *model_name
    model_registry_stage: 'production'
  data_input:
    table_name: 'holdout' 
  data_output:
    table_name: 'predictions'
    mode: 'overwrite'
